#+TITLE: Chameleon: A dense linear algebra software for heterogeneous architectures
#+LANGUAGE:  en
#+OPTIONS: H:3 num:t \n:nil @:t ::t |:t _:nil ^:nil -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil pri:nil tags:not-in-toc html-style:nil

Chameleon is a C library providing parallel algorithms to perform
BLAS/LAPACK operations exploiting fully modern architectures.

* Get Chameleon

  To use last development states of Chameleon, please clone the master
  branch. Note that Chameleon contains a ~git submodule~ *morse_cmake*.
  To get sources please use these commands:

  #+begin_src sh
  # if git version >= 1.9
  git clone --recursive git@gitlab.inria.fr:solverstack/chameleon.git
  cd chameleon
  # else
  git clone git@gitlab.inria.fr:solverstack/chameleon.git
  cd chameleon
  git submodule init
  git submodule update
  #+end_src

  Last releases of Chameleon are hosted on the [[https://gitlab.inria.fr/solverstack/chameleon/-/releases][releases page]].

* Documentations
** Homepage and user's guide
   Please visit our [[https://solverstack.gitlabpages.inria.fr/chameleon/][Homepage]] to get:
   * download links,
   * quick start guides,
   * installation instructions,
   * tutorials,
   * bencmarks.

   This documentation could also be generated in html:
   #+begin_src
   # build the doc with cmake (emacs with orgmode and latex are required), e.g.
   cmake .. -DCHAMELEON_ENABLE_DOC=ON
   make doc
   #+end_src
   see the ~doc/user~ directory.

** Source code documentation, API (doxygen)

   Please refer to the [[https://solverstack.gitlabpages.inria.fr/chameleon/dev/index.html][doxygen documentation]] to get more precise
   information about the API, the public and internal functions
   prototypes and the data structures.

   Please refer to the section 2.1 of [[file:READMEDEV.org][READMEDEV]] to get
   information about the documentation generation.

** For developers
   Please refer to the [[file:READMEDEV.org][READMEDEV]] page.

* Contact
  If you have an account on [[https://gitlab.inria.fr/][gitlab inria]] please submit a [[https://gitlab.inria.fr/solverstack/chameleon/-/issues][new issue]].

  If you don't have an account on [[https://gitlab.inria.fr][gitlab inria]] you can send emails to
  [[mailto:chameleon-issues@inria.fr][chameleon-issues@inria.fr]].

  To get the news, register to the mailing list
  [[https://sympa.inria.fr/sympa/info/chameleon-announce][chameleon-announce@inria.fr]] (click on "S'abonner" in the left
  panel).

* Get involved!
  [[file:CONTRIBUTING.org][CONTRIBUTING]]

* Licence
  [[file:LICENCE.txt][LICENCE]]
