FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt-get install git build-essential wget tar curl devscripts dh-make quilt pbuilder sbuild lintian svn-buildpackage git-buildpackage -y
RUN apt-get install gfortran cmake python pkg-config libopenblas-dev liblapacke-dev libstarpu-dev libopenmpi-dev libhwloc-dev -y

ARG GITLABTOKEN
ARG GITLABPROJNUM=616
ARG DEBIANDIST=ubuntu_20.04
ARG RELEASEVER="1.1.0"
ARG DEBIANARCH="1_amd64"
ARG RELEASETAR=chameleon-$RELEASEVER.tar.gz
ARG RELEASETARDEB=chameleon_$RELEASEVER.orig.tar.gz
ARG RELEASEURL=https://gitlab.inria.fr/solverstack/chameleon/uploads/b299d6037d7636c6be16108c89bc2aab/$RELEASETAR

RUN wget $RELEASEURL
RUN mv $RELEASETAR $RELEASETARDEB
RUN tar xvf $RELEASETARDEB

ENV LOGNAME=root
ENV DEBEMAIL=florent.pruvost@inria.fr
RUN cd /chameleon-$RELEASEVER/ && dh_make --library --yes

COPY changelog /chameleon-$RELEASEVER/debian/
COPY control /chameleon-$RELEASEVER/debian/
COPY copyright /chameleon-$RELEASEVER/debian/
COPY rules /chameleon-$RELEASEVER/debian/

RUN export DEB_BUILD_OPTIONS='nocheck' && cd /chameleon-$RELEASEVER/ && debuild -us -uc

RUN apt-get install ./chameleon_$RELEASEVER-$DEBIANARCH.deb -y
RUN export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && mpiexec -n 2 chameleon_stesting -t 2 -o gemm -n 1000

RUN git clone https://gitlab.inria.fr/solverstack/distrib.git
RUN cd /distrib/cmake/test/chameleon && mkdir build && cd build && cmake .. && make && ./test_chameleon

RUN curl --header "PRIVATE-TOKEN: ${GITLABTOKEN}" --upload-file ./chameleon_$RELEASEVER-$DEBIANARCH.deb "https://gitlab.inria.fr/api/v4/projects/$GITLABPROJNUM/packages/generic/$DEBIANDIST/$RELEASEVER/chameleon_$RELEASEVER-$DEBIANARCH.deb"